create database ESTUDOCASOIII;
use ESTUDOCASOIII;
drop database ESTUDOCASOIII;

CREATE TABLE usuarios (
    ID_USUARIO INT PRIMARY KEY,
    NOME_USUARIO VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL
);

CREATE TABLE grupos (
    ID_GRUPO INT PRIMARY KEY,
    NOME_GRUPO VARCHAR(100) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE usuarios_grupos (
    USUARIO INT NOT NULL,
    GRUPO INT NOT NULL,
    PRIMARY KEY (USUARIO, GRUPO),
    FOREIGN KEY (USUARIO) REFERENCES usuarios(ID_USUARIO),
    FOREIGN KEY (GRUPO) REFERENCES grupos(ID_GRUPO)
);

CREATE TABLE seguidores_usuarios (
    USUARIO INT NOT NULL,
    SEGUIDOR INT NOT NULL,
    PRIMARY KEY (USUARIO, SEGUIDOR),
    FOREIGN KEY (USUARIO) REFERENCES usuarios(ID_USUARIO),
    FOREIGN KEY (SEGUIDOR) REFERENCES usuarios(ID_USUARIO)
);

CREATE TABLE postagens (
    ID_POST INT PRIMARY KEY,
    TEXTO TEXT NOT NULL,
    IMAGEM BLOB,
    DATA_HORA DATETIME NOT NULL,
    USUARIO INT NOT NULL,
    FOREIGN KEY (USUARIO) REFERENCES usuarios(ID_USUARIO)
);

CREATE TABLE comentarios (
    ID_COMENTARIO INT PRIMARY KEY,
    TEXTO TEXT NOT NULL,
    DATAHORA DATETIME NOT NULL,
    USUARIO INT NOT NULL,
    POST INT NOT NULL,
    FOREIGN KEY (USUARIO) REFERENCES usuarios(ID_USUARIO),
    FOREIGN KEY (POST) REFERENCES postagens(ID_POST)
);
